---
# tasks file for ansible-role-wifimonbuild

- debug:
    msg:
    - "This is ansible-role-wifimonbuild!"

- name: Install Maven
  apt:
    name: maven
    update_cache: yes

- name: install wifimon
  apt:
    deb: https://fl-5-205.unil.cloud.switch.ch/wifimon-agent-0.1.1-SNAPSHOT.deb
  tags: wifimon

- name: Clone Bitbucket Repo
  git: >
    repo=https://bitbucket.software.geant.org/scm/wfmon/agent.git
    dest=/tmp/wifimon/agent

- name: copy subnets file
  copy:
    src: ./roles/ansible-role-wifimonbuild/files/elasticsearchSubnets_a_b_c_d_xx.html 
    dest: /tmp/wifimon/agent/wifimon-ui/src/main/resources/templates/secure/

- name: copy subnets file
  copy:
    src: ./roles/ansible-role-wifimonbuild/files/elasticsearchHWProbesx.html 
    dest: /tmp/wifimon/agent/wifimon-ui/src/main/resources/templates/secure/

- name: Compile Wifimon Code
  command:
    cmd: "mvn clean install" 
    chdir: /tmp/wifimon/agent

- name: Maven package run
  command:
    cmd: "mvn package"
    chdir: /tmp/wifimon/agent

- name: copy war files
  copy:
    src: /tmp/wifimon/agent/wifimon-assembly/target/wifimon-agent-bin/secure-processor-0.1.1-SNAPSHOT.war
    dest: /usr/lib/wifimon/secure-processor-0.1.1.war
    force: yes
    remote_src: yes

- name: copy war files
  copy:
    src: /tmp/wifimon/agent/wifimon-assembly/target/wifimon-agent-bin/ui-0.1.1-SNAPSHOT.war
    dest: /usr/lib/wifimon/ui-0.1.1.war
    force: yes
    remote_src: yes


